spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/BASurveyApp
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
jwt:
  secret: 546A576E5A7234753778214125442A472D4B6150645367566B58703273357638


feign:
  url: http://localhost:8081